refactor(landscape): implement landscape click open page,HW-4
nodir-sulaymonov/android-project pull request #4
Opened 2020-11-17 17:40 UTC by nodir-sulaymonov

refactor(landscape): implement landscape click open page,HW-4

2020-11-21 20:28 UTC, IvanShafran requested changes

2020-11-21 20:28 UTC, IvanShafran commented on app/src/main/res/layout/second_page.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
И в portrait, и в landcape ориентации будет горизонтально элементы располагаться.
Нужно, чтобы по-разному. Проверь дизайн:
https://www.figma.com/file/3obxttQLnd5Jl2YS2i62jl/Homework-4?node-id=0%3A1

Для этого нужно создать второй layout в папке layout-land
Нагуглил такой туториал:https://www.geeksforgeeks.org/designing-the-landscape-and-portrait-mode-of-application-in-android/

2020-11-25 15:33 UTC, nodir-sulaymonov commented on app/src/main/res/layout/second_page.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
@IvanShafran Всё исправил можешь посмотреть

2020-11-29 17:12 UTC, IvanShafran approved these changes
Good job

2020-11-29 17:15 UTC, merged